### ISSUE TITLE
Example in documentation does not work

### ISSUE THREAD

**Issue by TanyaKovalenko** [DmitryPogrebnoy/MedSpellChecker#1]
Hello, I am trying to run this example, but the spellchecker fixes only the word "инфаркт". What is the problem? (I tried all other supported candidate rankers from the documentation)

```python
from medspellchecker.tool.medspellchecker import MedSpellchecker
from medspellchecker.tool.distilbert_candidate_ranker import RuDistilBertCandidateRanker

candidate_ranker = RuDistilBertCandidateRanker()
spellchecker = MedSpellchecker(candidate_ranker)
fixed_text = spellchecker.fix_text(
    "У больногодиагностирован инфркт и тубркулез"
)

print(fixed_text)
```

"У больного диагностирован инфаркт и туберкулез"   - **SHOULD GET**

**BUT I GOT**: "У больногодиагностирован инфаркт и тубркулез"

**Comment by DmitryPogrebnoy** [comment]
Hello! Sorry for the inconvenience. It was a bit outdated example. I updated it and now it's correct. See commit ed4ae26

**Comment by TanyaKovalenko** [comment]
Thanks a lot =)
